/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package lab1;
import java.util.Random;


// import java.sql.Time;
// import java.text.BreakIterator;
// LocalDateTime.now() method
import java.time.*;

public class App {
    public static String pluralize(String animal, int num) {
        if (num == 1 || num == 0) {
            return animal;
        } else {
            return animal + 's';
        }

    }

    public static void main(String[] args) {

        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");

        clock();
        flipNHeads(2);

    }

    public static void flipNHeads(int n) {
       int counter=0;
       int heads =0;
       while (heads<n){
           Random random = new Random();
           if (random.nextDouble()<0.5) {
            counter++;
            heads=0;
            System.out.println("tail");
           }
           else {
               counter++;
               heads++;
               System.out.println("heads");
           }
       }
       System.out.println("It took " + counter + " flips to flip " + n + " heads in a row.");

    }

    public static void clock() {
        while (true) {
            LocalDateTime now = LocalDateTime.now();
            int hour = LocalDateTime.now().getHour();
            int minute = LocalDateTime.now().getMinute();

            int second = now.getSecond();
            while (second == LocalDateTime.now().getSecond()) {
                continue;
            }
            System.out.println(now);
            System.out.println(hour + ":" + minute + ":" + second + "   ");
        }
        // LocalDateTime now = LocalDateTime.now();
        // System.out.println(now);
    }

}
