/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package lab1;
import java.util.Random;

import java.sql.Time;
import java.text.BreakIterator;
// LocalDateTime.now() method
import java.time.*;

public class App {
    public static String pluralize(String animal, int num) {
        if (num == 1 || num == 0) {
            return animal;
        } else {
            return animal + 's';
        }

    }

    public static void main(String[] args) {

        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");

        // clock();
        flipNHeads(2);

    }

    public static void flipNHeads(int n) {
        Random rand = new Random();
        int upperbound = 1;
        double random=rand.nextDouble();
        // double random = (int) Math.floor(Math.random() * (1 - 0 + 1) + 0);
        System.out.println(random);
        if (random < 0.5) {
            System.out.println("Head");

        } else {
            System.out.println("tail");
        }

        while (random < .5) {
continue;
        }

    }

    public static void clock() {
        while (true) {
            LocalDateTime now = LocalDateTime.now();

            int second = now.getSecond();
            while (second == LocalDateTime.now().getSecond()) {
                continue;
            }
            System.out.println(now);
        }
        // LocalDateTime now = LocalDateTime.now();
        // System.out.println(now);
    }

}
